GET http://localhost:4040/api/users/All

###
GET http://localhost:4040/api/users/3


###
POST http://localhost:4040/api/users/ADD HTTP/1.1
Content-Type: application/json

{
    "first_name":"armin",
    "last_name":"nostati",
    "user_name":"user_armin",
    "password":"1234I21"
}


###
PUT http://localhost:4040/api/users/UPDATE HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "first_name":"RRRRRR",
    "last_name":"azizi",
    "user_name":"user_kamal",
    "password":"hashed_password_2"
}



###
DELETE http://localhost:4040/api/users/DELETE/4
